### ISSUE TITLE
smol issue : size badge doesn't appear on Chrome

### ISSUE THREAD

**Issue by EDM115** [jazzypants1989/jessquery#5]
![image](https://github.com/jazzypants1989/jessquery/assets/82015596/06e58c90-effc-460f-95e5-eb8ff052271f)
  
chrome enforces Cross-Origin Read Blocking (CORB) policy, which makes the badge not loading up  
  
note that the original image shows :  
![image](https://github.com/jazzypants1989/jessquery/assets/82015596/a1abfd64-f8de-4123-a395-765d397b6729)
and the github proxied one shows too (in a new tab) :  
![image](https://github.com/jazzypants1989/jessquery/assets/82015596/dee760a7-8c51-4d76-bcc5-4bdc665b0814)

**Comment by jazzypants1989** [comment]
Dang, I was wondering why that was being so flaky and bothersome! Do you know why the NPM one seems to consistently work in contrast?

**Comment by EDM115** [comment]
![image](https://github.com/jazzypants1989/jessquery/assets/82015596/af1ee45f-31a0-43a9-8328-da02b7012771)  
for the weirdest reasons it works now  
but i will still search what causes the bug :)

**Comment by EDM115** [comment]
is there any source/presentation page for the first badge endpoint ?  
~~none of my searches shows any result~~ nvm, found https://twitter.com/jsbundle/status/1634455567321255936?s=20

**Comment by jazzypants1989** [comment]
Okay, thanks for doing the research! I really appreciate it.

I'm gonna go ahead and close this. I don't really mind if people see the alt-text sometimes lol.
